/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.view;
import calculadora.controllers.CalculadoraController;
/**
 *
 * @author usuario
 */
public class CalculadoraPadraoView extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraView
     */
    public CalculadoraPadraoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtTela = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBtnPorcentagem = new javax.swing.JButton();
        jBtnMaisMenos = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnDivisao = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnMultiplicacao = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnSubtracao = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBtn0 = new javax.swing.JButton();
        jBtnPoint = new javax.swing.JButton();
        jBtnIgual = new javax.swing.JButton();
        jBtnAdicao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCalculadora = new javax.swing.JMenu();
        jMnPadrao = new javax.swing.JMenuItem();
        jMnCience = new javax.swing.JMenuItem();
        jMnProgram = new javax.swing.JMenuItem();
        jMenuConversor = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxtTela.setEditable(false);
        jTxtTela.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTxtTela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtTela.setText("0");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jBtnPorcentagem.setText("%");
        jPanel1.add(jBtnPorcentagem);

        jBtnMaisMenos.setText("+/-");
        jBtnMaisMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMaisMenosActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMaisMenos);

        jBtnClear.setText("CE");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnClear);

        jBtnBack.setText("<-");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnBack);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel2.add(jBtn7);

        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel2.add(jBtn8);

        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel2.add(jBtn9);

        jBtnDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao(evt);
            }
        });
        jBtnDivisao.setText("/");
        jPanel2.add(jBtnDivisao);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel3.add(jBtn4);

        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel3.add(jBtn5);

        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel3.add(jBtn6);

        jBtnMultiplicacao.setText("*");
        jBtnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao(evt);
            }
        });
        jPanel3.add(jBtnMultiplicacao);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel4.add(jBtn1);

        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel4.add(jBtn2);

        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel4.add(jBtn3);

        jBtnSubtracao.setText("-");
        jBtnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao(evt);
            }
        });
        jPanel4.add(jBtnSubtracao);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel5.add(jBtn0);

        jBtnPoint.setText(".");
        jBtnPoint.setAutoscrolls(true);
        jBtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitar(evt);
            }
        });
        jPanel5.add(jBtnPoint);

        jBtnIgual.setText("=");
        jBtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIgualActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnIgual);

        jBtnAdicao.setText("+");
        jBtnAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacao(evt);
            }
        });
        jPanel5.add(jBtnAdicao);

        jMenuCalculadora.setText("Calculadoras");

        jMnPadrao.setText("Padrão");
        jMenuCalculadora.add(jMnPadrao);

        jMnCience.setText("Científica");
        jMenuCalculadora.add(jMnCience);

        jMnProgram.setText("Programador");
        jMenuCalculadora.add(jMnProgram);

        jMenuBar1.add(jMenuCalculadora);

        jMenuConversor.setText("Conversores");
        jMenuBar1.add(jMenuConversor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtTela)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtTela, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    CalculadoraController calc = new CalculadoraController();
    
    private String trataInteiro(Double x1){
        
        int x2 = x1.intValue();
        
        if(x1>x2){
            return String.format("%.5f", x1).replace(',', '.');
        }
        else{
            return Integer.toString(x2);
        }
        
    }
    
    private void jBtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIgualActionPerformed
        double y = Double.parseDouble(jTxtTela.getText());
        calc.setB(y);
        calc.igual();
        jTxtTela.setText(trataInteiro(calc.getRes()));
        
    }//GEN-LAST:event_jBtnIgualActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        jTxtTela.setText("0");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnMaisMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMaisMenosActionPerformed
        double n = Double.parseDouble(jTxtTela.getText());
        n = n*-1;
        jTxtTela.setText(trataInteiro(n));
    }//GEN-LAST:event_jBtnMaisMenosActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        String apagado = jTxtTela.getText().substring(0, jTxtTela.getText().length()-1);
        jTxtTela.setText(apagado);
        
        if(jTxtTela.getText().isEmpty()){
            jTxtTela.setText("0");
        }
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void operacao(java.awt.event.ActionEvent evt){
        double x = Double.parseDouble(jTxtTela.getText());
        char op = evt.getActionCommand().charAt(0);
        calc.setA(x);
        calc.setOp(op);
        jTxtTela.setText("");
    }
    
    private void digitar(java.awt.event.ActionEvent evt){
        if(jTxtTela.getText().compareTo("0")==0){
            jTxtTela.setText("");
        }
        
        if(jTxtTela.getText().length()<=10){
            if(evt.getActionCommand().charAt(0) != '.' || jTxtTela.getText().indexOf('.') == -1){
                jTxtTela.setText(jTxtTela.getText()+evt.getActionCommand());
            }
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPadraoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPadraoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPadraoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraPadraoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraPadraoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAdicao;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDivisao;
    private javax.swing.JButton jBtnIgual;
    private javax.swing.JButton jBtnMaisMenos;
    private javax.swing.JButton jBtnMultiplicacao;
    private javax.swing.JButton jBtnPoint;
    private javax.swing.JButton jBtnPorcentagem;
    private javax.swing.JButton jBtnSubtracao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCalculadora;
    private javax.swing.JMenu jMenuConversor;
    private javax.swing.JMenuItem jMnCience;
    private javax.swing.JMenuItem jMnPadrao;
    private javax.swing.JMenuItem jMnProgram;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTxtTela;
    // End of variables declaration//GEN-END:variables
}
